version: '3.9'
services:
  db:
    image: postgres:14  # Specify version for consistency
    container_name: pdf-postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"  # PostgreSQL
    environment:   
      POSTGRES_PASSWORD: password  # Set your desired password
      POSTGRES_USER: postgres      # Specify the username
      POSTGRES_DB: pdf_data        # Specify the database name
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: fastapi-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db  # Ensure PostgreSQL starts before backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: vite-frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/front-end-dm-agent:/app/frontend/front-end-dm-agent
      - frontend_node_modules:/app/frontend/front-end-dm-agent/node_modules
    depends_on:
      - backend       

volumes:
  db_data:
  frontend_node_modules:
